import {db,scheduler} from "hatchable";
export const access="user"; export const methods=["PUT"];
const at=s=>{const[y,m,d]=s.split("-").map(Number);return new Date(Date.UTC(y,m-1,d,9)-86400000)};
const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(String(s||""));
export default async function(req,res){
 const b=req.body||{},interval=Number(b.interval_days);
 if(!b.id||!b.name||!b.frequency||!b.due_date)return res.status(400).json({error:"Required bill fields are missing."});
 if(b.end_date&&(!validDate(b.end_date)||b.end_date<b.due_date))return res.status(400).json({error:"End date must be empty or on/after the due date."});
 if(b.frequency==="custom"&&(!Number.isInteger(interval)||interval<1||interval>3650))return res.status(400).json({error:"Custom interval must be between 1 and 3650 days."});
 const old=(await db.query("SELECT reminder_task_id,status FROM bills WHERE id=$1 AND user_id=$2",[b.id,req.user.id])).rows[0];if(!old)return res.status(404).json({error:"Bill not found."});
 if(old.reminder_task_id)try{await scheduler.cancel(old.reminder_task_id)}catch{}
 const {rows}=await db.query("UPDATE bills SET name=$1,amount=$2,currency=$3,category=$4,frequency=$5,interval_days=$6,due_date=$7,end_date=$8,due_day=$9,reminder_enabled=$10,notes=$11,reminder_email=$12,payment_method_id=$13,payment_method_name=$14,payment_card_last4=$15,subscription_id=$16,session_target=$17,session_count=CASE WHEN $5='session_based' THEN COALESCE(session_count,0) ELSE NULL END,session_weekdays=$18,session_next_date=$19,session_cycle=CASE WHEN $5='session_based' THEN COALESCE(session_cycle,1) ELSE NULL END,session_payment_timing=CASE WHEN $5='session_based' THEN CASE WHEN $20='first_session' THEN 'first_session' ELSE 'last_session' END ELSE NULL END,reminder_task_id=NULL,updated_at=NOW() WHERE id=$21 AND user_id=$22 RETURNING id,name,amount,currency,category,frequency,interval_days,due_date,end_date,due_day,reminder_enabled,notes,status,paused_at,payment_status,paid_at,remind_at,payment_method_id,payment_method_name,payment_card_last4,subscription_id,session_target,session_count,session_weekdays,session_next_date,session_cycle,session_payment_timing",[String(b.name).trim(),b.amount===""||b.amount==null?null:Number(b.amount),b.currency||"USD",b.category||null,b.frequency,b.frequency==="custom"?interval:null,b.due_date,b.end_date||null,b.due_day?Number(b.due_day):null,b.reminder_enabled!==false,b.notes||null,req.user.email||null,b.payment_method_id||null,b.payment_method_name||null,b.payment_card_last4?String(b.payment_card_last4).replace(/\D/g,"").slice(-4):null,b.subscription_id||null,b.frequency==="session_based"?Math.max(1,Math.min(3650,Number(b.session_target)||1)):null,b.frequency==="session_based"?String(b.session_weekdays||""):null,b.frequency==="session_based"?(b.session_next_date||b.due_date):null,b.frequency==="session_based"?(b.session_payment_timing==="first_session"?"first_session":"last_session"):null,b.id,req.user.id]);
 const bill=rows[0];
 if(bill.status==="active"&&bill.reminder_enabled&&bill.frequency!=="one_time"&&bill.frequency!=="session_based"){const when=at(bill.due_date);if(when>new Date()&&(!bill.end_date||bill.due_date<=bill.end_date)){const task=await scheduler.at(when,"/api/reminders/send",{payload:{billId:bill.id},name:"bill-reminder-"+bill.id});await db.query("UPDATE bills SET reminder_task_id=$1 WHERE id=$2",[task.id,bill.id]);}}
 res.json({bill});
}